import MainNavigation from "../component/MainNavigation";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
      <MainNavigation/>
      <main>{children}</main>
      </body>
    </html>
  );
}
